//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FethlerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SeferGorev
    {
        public int Gorev_id { get; set; }
        public Nullable<int> Arac_id { get; set; }
        public Nullable<int> Sofor_id { get; set; }
        public string Gorevli_ids { get; set; }
        public string Köyler { get; set; }
        public Nullable<int> Bölge { get; set; }
        public string Koy_ids { get; set; }
        public string Gorevli { get; set; }
        public Nullable<int> PaketSayisi { get; set; }
        public Nullable<int> cikisSirasi { get; set; }
    
        public virtual tbl_Araclar tbl_Araclar { get; set; }
        public virtual tbl_Bolgeler tbl_Bolgeler { get; set; }
        public virtual tbl_Gorevliler tbl_Gorevliler { get; set; }
    }
}
